# Generated by Django 3.2.9 on 2021-12-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='code',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
