# Generated by Django 3.2.9 on 2021-12-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('custom-order', 'Custom Order'), ('general', 'General'), ('review', 'Review'), ('suggestion', 'Suggestion'), ('catering-request', 'Catering Request')], max_length=20),
        ),
    ]
