# Generated by Django 3.2.9 on 2021-12-10 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macaron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Macaron',
                'verbose_name_plural': 'Macarons',
            },
        ),
        migrations.CreateModel(
            name='MacaronCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for entire collection.', max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Discounted price for entire collection.', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Macaron Collection',
                'verbose_name_plural': 'Macaron Collections',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free'), ('Halal', 'Halal'), ('Nut Free', 'Nut Free')], max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='MacaronSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=6, help_text='Number of macarons per box.')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of <b>each</b> macaron. <b>NOT</b> price of entire box.', max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of <b>each</b> macaron. <b>NOT</b> price of entire box.', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macaron', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='shop.macaron')),
            ],
            options={
                'verbose_name': 'Macaron Set',
                'verbose_name_plural': 'Macaron Sets',
            },
        ),
        migrations.CreateModel(
            name='MacaronImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='macarons/images/')),
                ('alt_text', models.CharField(max_length=120)),
                ('caption', models.TextField(max_length=5000)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macaron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.macaron')),
            ],
            options={
                'verbose_name': 'Macaron Image',
                'verbose_name_plural': 'Macaron Images',
            },
        ),
        migrations.CreateModel(
            name='MacaronCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=3)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macaron', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='shop.macaron')),
            ],
            options={
                'verbose_name': 'Macaron Collection Item',
                'verbose_name_plural': 'Macaron Collection Items',
            },
        ),
        migrations.CreateModel(
            name='MacaronCollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='macarons/images/collection/')),
                ('alt_text', models.CharField(max_length=120)),
                ('caption', models.TextField(max_length=5000)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.macaroncollection')),
            ],
            options={
                'verbose_name': 'Macaron Collection Image',
                'verbose_name_plural': 'Macaron Collection Images',
            },
        ),
        migrations.AddField(
            model_name='macaroncollection',
            name='macarons',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='shop.MacaronCollectionItem'),
        ),
        migrations.AddField(
            model_name='macaron',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='shop.Tag'),
        ),
    ]
