# Generated by Django 3.2.9 on 2021-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211212_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaronimage',
            name='order',
        ),
        migrations.AddField(
            model_name='macaronset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
