# Generated by Django 3.2.9 on 2021-12-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_macaroncollection_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaroncollection',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for entire collection.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='macaroncollection',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discounted price for entire collection.', max_digits=5),
        ),
    ]
