# Generated by Django 3.2.9 on 2021-12-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20211212_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacaronCustomCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='macaroncollection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='macaronset',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.CreateModel(
            name='MacaronCustomCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=6)),
                ('disclaimer', models.TextField(help_text='Message presented to the user on how to create a custom collection.', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Macaron Custom Collection',
                'verbose_name_plural': 'Macaron Custom Collections',
            },
        ),
    ]
