# Generated by Django 3.2.9 on 2021-12-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211223_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macaroncustomcollection',
            name='user',
        ),
    ]
