# Generated by Django 3.2.9 on 2021-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211203_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaroncollection',
            name='macarons',
            field=models.ManyToManyField(limit_choices_to={'active': True}, related_name='macarons', to='shop.MacaronCollectionItem'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Gluten Free', 'Gluten Free'), ('Halal', 'Halal'), ('Nut Free', 'Nut Free')], max_length=40, unique=True),
        ),
    ]
