# Generated by Django 3.2.9 on 2021-12-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211203_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaroncollection',
            name='macarons',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='shop.MacaronCollectionItem'),
        ),
    ]
