# Generated by Django 3.2.9 on 2021-12-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_macaroncustomcollection_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macaron', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='shop.macaron')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Macaron Custom Collection Item',
                'verbose_name_plural': 'Macaron Custom Collection Items',
            },
        ),
        migrations.RenameModel(
            old_name='MacaronCollection',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='MacaronCollectionImage',
            new_name='CollectionImage',
        ),
        migrations.RenameModel(
            old_name='MacaronCollectionItem',
            new_name='CollectionItem',
        ),
        migrations.RenameModel(
            old_name='MacaronCustomCollection',
            new_name='CustomCollectionDeclaration',
        ),
        migrations.RenameModel(
            old_name='MacaronImage',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='MacaronSet',
            new_name='Set',
        ),
        migrations.DeleteModel(
            name='MacaronCustomCollectionItem',
        ),
        migrations.AlterModelOptions(
            name='customcollectiondeclaration',
            options={'verbose_name': 'Macaron Custom Collection Declaration', 'verbose_name_plural': 'Macaron Custom Collection Declarations'},
        ),
    ]
