# Generated by Django 3.2.9 on 2021-12-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_macaroncollection_macarons'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaroncollection',
            name='description',
            field=models.TextField(default='test description', max_length=5000),
            preserve_default=False,
        ),
    ]
