# Generated by Django 3.2.9 on 2021-12-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_macaroncollection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacaronImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='macarons/images/')),
                ('alt_text', models.CharField(max_length=120)),
                ('caption', models.TextField(max_length=5000)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('macaron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.macaron')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
