# Generated by Django 3.2.9 on 2021-12-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customcollection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomCollectionDeclaration',
            new_name='CustomCollectionType',
        ),
    ]
