# Generated by Django 3.2.9 on 2021-12-05 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211205_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macaronimage',
            name='macaron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.macaron'),
        ),
    ]
