# Generated by Django 3.2.9 on 2021-12-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211223_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='notes',
            field=models.TextField(default='test', max_length=5000),
            preserve_default=False,
        ),
    ]
