# Generated by Django 3.2.9 on 2021-12-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customcollection_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customcollectionitem',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customcollectiontype',
            name='name',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
