# Generated by Django 3.2.9 on 2021-12-05 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_macaronimage_macaron'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacaronCollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='macarons/images/collection/')),
                ('alt_text', models.CharField(max_length=120)),
                ('caption', models.TextField(max_length=5000)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.macaroncollection')),
            ],
            options={
                'verbose_name': 'Macaron Collection Image',
                'verbose_name_plural': 'Macaron Collection Images',
            },
        ),
    ]
