# Generated by Django 3.2.9 on 2021-12-24 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211223_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcollection',
            name='macarons',
        ),
        migrations.RemoveField(
            model_name='customcollection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customcollectionitem',
            name='macaron',
        ),
        migrations.RemoveField(
            model_name='customcollectionitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomCollectionType',
        ),
        migrations.DeleteModel(
            name='CustomCollection',
        ),
        migrations.DeleteModel(
            name='CustomCollectionItem',
        ),
    ]
