# Generated by Django 3.2.9 on 2021-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_macaroncollectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaroncollection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='macaronset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
