# Generated by Django 3.2.9 on 2021-12-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcollection',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
