# Generated by Django 3.2.9 on 2021-12-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_customcollection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCollectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField(max_length=1000)),
                ('quantity', models.PositiveIntegerField(default=6, help_text='Quantity for the entire collection (6 or 12)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the entire custom collection', max_digits=5)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount price for the entire custom collection', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customcollection',
            name='code',
        ),
        migrations.AlterField(
            model_name='customcollection',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customcollection',
            name='type',
            field=models.ForeignKey(default=0, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_collections', to='shop.customcollectiontype'),
            preserve_default=False,
        ),
    ]
