# Generated by Django 3.2.9 on 2021-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
