# Generated by Django 3.2.9 on 2021-12-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in-progress', 'In Progress'), ('ready-for-pickup', 'Ready for Pickup')], default='created', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
