# Generated by Django 3.2.9 on 2021-12-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in-progress', 'In Progress'), ('ready-for-pickup', 'Ready for Pickup'), ('completed', 'Completed')], max_length=50),
        ),
    ]
